import img1 from '../../assets/im1.jpg'
import img2 from '../../assets/im2.jpg'
import img3 from '../../assets/im3.jpg'
import img4 from '../../assets/im4.jpg'
import img5 from '../../assets/im5.jpg'
import img6 from '../../assets/im6.jpg'
import img7 from '../../assets/collection/img7.jpg'
import img8 from '../../assets/collection/img8.jpg'
import img9 from '../../assets/collection/img9.jpg'
export default [img1,img2,img3,img4,img5,img6,img7,img8,img9]